blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, PasswordResetView1, verify, success, verify_email

from django.contrib.auth import views as auth_views

from django.views.decorators.cache import never_cache

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', never_cache(ProfileView.as_view()), name='profile'),
    path('verify/<str:token>', verify),
    path('success/', success, name='success'),
    path('verify_email/', verify_email, name='verify'),

    # password reset urls
    path('password_reset/', PasswordResetView1.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/models.py
from django.db import models


NULLABLE = {'null': True, 'blank': True}


# create new model, after creating write makemigrations, migrate
class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name='slug')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    create_date = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from catalog.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image',)


class BlogUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'is_published',)

blog/views.py
from catalog.views import UserIsVerified
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm, BlogUpdateForm
from blog.models import Blog

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class BlogCreateView(LoginRequiredMixin, UserIsVerified, CreateView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UserIsVerified, UpdateView):
    model = Blog
    form_class = BlogUpdateForm
    # success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        # args=[self.kwargs.get('pk')] 'pk' we get from urls.py  "path('view/<int:pk>/'..." in any methods
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, UserIsVerified, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


class BlogListView(LoginRequiredMixin, UserIsVerified, ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, UserIsVerified, DetailView):
    model = Blog

    # method to increase views count in blog_detail.html
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}


    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-5 shadow">
            <div class="modal-body p-9 text-center">
                <h5 class="mb-0">Delete this blog?</h5>
                <p class="mb-0">{{ object.title }}</p>
            </div>
            <form class="modal-footer flex-nowrap p-0" method="post">
                {% csrf_token %}
                <button type="submit"
                        class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">
                    <strong>Yes, delete</strong></button>
                <a href="{% url 'blog:blog_list' %}" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0"
                        data-bs-dismiss="modal">No, cancel
                </a>
            </form>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<style>
p {
    word-break: break-all;
    white-space: normal;
}
</style>

<article class="blog-post">
    <div>
        <h2 align="center" class="display-5 link-body-emphasis mb-1">{{ object.title }}</h2>

        <img src="/media/{{object.image}}"/>
        <p class="fw-light">{{ object.create_date }}, <a href="#">user</a></p>
        <p>
            {{ object.content }}
        </p>
        <hr>
    </div>
</article>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}

{% if user.is_authenticated %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>To add blog click button below </h4>
        </div>
        <div class="card-body">
            <a class="btn btn-outline-dark" type="button" href="{% url 'blog:blog_create' %}">Add Blog</a>
        </div>
    </div>
    <br>
</div>
{% else %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h5>You cannot add blogs, first sign up or log in to your account</h5>
        </div>
        <div class="card-body">
            <a class="btn btn-outline-dark" type="button" href="{% url 'users:register' %}">SignUp</a>
            <a class="btn btn-outline-dark" type="button" href="{% url 'users:login' %}">LogIn</a>
        </div>
    </div>
    <br>
</div>


{% endif %}

{% for object in object_list %}
<div class="col-6">
    <div class="card">
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
            <h2>{{ object.title }}</h2>
            <p>{{object.content|slice:"0:100"}}...</p>
            <a href="{% url 'blog:blog_view' object.pk %}" class="btn btn-outline-primary" type="button">View</a>
            <a href="{% url 'blog:blog_edit' object.pk %}" class="btn btn-outline-secondary" type="button">Edit</a>
            <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-outline-danger" type="button">Delete</a>
        </div>
    </div>
    <br>
</div>
{% endfor %}
{% endblock %}