blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, PasswordResetView1, verify, success, verify_email

from django.contrib.auth import views as auth_views

from django.views.decorators.cache import never_cache

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', never_cache(ProfileView.as_view()), name='profile'),
    path('verify/<str:token>', verify),
    path('success/', success, name='success'),
    path('verify_email/', verify_email, name='verify'),

    # password reset urls
    path('password_reset/', PasswordResetView1.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django_countries.fields import CountryField

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    """Creating User model inherit only from AbstractUser"""
    username = None  # turn off login through username
    email = models.EmailField(unique=True, verbose_name='email')

    phone = models.CharField(max_length=35, verbose_name='номер', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = CountryField(verbose_name='страна',
                           **NULLABLE)  # installed package django-countries with pyuca translation
    token = models.CharField(max_length=100, default=uuid.uuid4)
    is_verified = models.BooleanField(default=False, verbose_name='Верифицирован')

    USERNAME_FIELD = "email"  # through what log in
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            (
                'check_verification',
                'Can check email verification of account'
            )
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar', 'is_verified')
        widgets = {
            'is_verified': forms.TextInput(attrs={'disabled': True}),
        }

    def __init__(self, *args, **kwargs):
        """This need to do not show:
        "No password set.
        Raw passwords are not stored, so there is no way to see this user’s password,
        but you can change the password using this form."
        This message when updating profile
        """
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from catalog.views import UserIsVerified
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail

from django.contrib.auth.mixins import LoginRequiredMixin


def verify_email(request):
    context = {
        'title': 'Verify email'
    }
    return render(request, 'users/verify_email.html', context)


def success(request):
    context = {
        'title': 'Success sign up'
    }
    return render(request, 'users/success.html', context)


def verify(request, token):
    try:
        user = get_object_or_404(User, token=token)
        if user:
            user.is_verified = True
            user.save()
            print(user.__dict__)
            msg = 'Your email verified'
            return render(request, 'info.html', {'msg': msg})
    except Exception as e:
        msg = e
        return render(request, 'info.html', {'msg': msg})


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:success')

    def form_valid(self, form):
        self.object = form.save()
        domain_name = get_current_site(self.request).domain
        print(self.object)
        print(f'token user {self.object.token}')
        link = f'http://{domain_name}/users/verify/{str(self.object.token)}'
        print(link)

        send_mail(
            "Email Verification",
            f"Click the link-> {link} to verify",
            settings.EMAIL_HOST_USER,
            [self.object.email],
            fail_silently=False,
        )
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UserIsVerified, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """this need to do not provide pk to update profile"""
        return self.request.user


class PasswordResetView1(LoginRequiredMixin, UserIsVerified, PasswordResetView):
    from_email = settings.EMAIL_HOST_USER
    success_url = reverse_lazy("users:password_reset_done")

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Login
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
                <div class="card-footer">
                    <p><a href="{% url 'users:password_reset' %}">Forgot your password?</a></p>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Registration
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Sign up</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/success.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4 align="center">Congrats, you have signed up, please check your email, to verify</h4>
        </div>
        <div class="card-body">
            <p align="center"><a href="{% url 'users:login' %}" type="submit" class="btn btn-outline-primary">Click to
                log in</a></p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Profile
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save</button>

                    <a href="{% url 'users:password_reset' %}" type="submit" class="btn btn-outline-primary">Reset password</a>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/verify_email.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4 align="center">You need to verify your email, to use this web site</h4>
        </div>
        <div class="card-body">
            <p align="center">Check your email {{ user.email }}</p>
        </div>
    </div>
</div>
{% endblock %}