blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import home, contact, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, category_list

from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    # products
    path('products/', ProductListView.as_view(), name='products'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete_product'),
    # categories
    path('categories/', cache_page(60)(category_list), name='list_category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, PasswordResetView1, verify, success, verify_email

from django.contrib.auth import views as auth_views

from django.views.decorators.cache import never_cache

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', never_cache(ProfileView.as_view()), name='profile'),
    path('verify/<str:token>', verify),
    path('success/', success, name='success'),
    path('verify_email/', verify_email, name='verify'),

    # password reset urls
    path('password_reset/', PasswordResetView1.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

catalog/models.py
from django.db import models
from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименования категории')
    description = models.TextField(**NULLABLE, verbose_name='Описание категории')
    created_at = models.DateTimeField(auto_now=True, verbose_name='дата создания категории')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименования')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    image = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    # category = models.CharField(max_length=100, verbose_name='Категория')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now=True, verbose_name='дата создания')
    date_last_change = models.DateTimeField(auto_now=True, verbose_name='дата изменения')
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')

    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False, **NULLABLE,
                             verbose_name='Пользователь')

    def __str__(self):
        return f'{self.name}, ({self.category})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

        permissions = [
            ('set_published', 'Can publish posts'),
            ('can_change_description_and_category', 'Can change description and category'),
        ]


class Version(models.Model):
    number = models.CharField(max_length=100, verbose_name='номер версии')
    name = models.CharField(max_length=150, verbose_name='название версии')
    tag = models.BooleanField(default=True, verbose_name='признак версии')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

BAD_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция']
COUNT = []


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class ProductCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'  # use all fields
        # fields = ('name',)  # use only listed fiedls
        exclude = ('user',)  # use all except these
        # write only one option

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        for bad in BAD_WORDS:
            if bad in cleaned_data:
                raise forms.ValidationError('Ошибка, связанная с плохими словами в названии')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        for bad in BAD_WORDS:
            if bad in cleaned_data:
                raise forms.ValidationError('Ошибка, связанная с плохими словами в названии')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from catalog.services import get_queryset_from_models
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductCreateForm, VersionForm
from catalog.models import Product, Version, Category

from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin

from django.http import Http404


class UserIsVerified(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_verified


@login_required
@user_passes_test(lambda u: u.is_verified, login_url='users/verify_email/')
def home(request):
    context = {
        'title': 'Home page'
    }
    return render(request, 'catalog/home.html', context)


@login_required
def contact(request):
    context = {
        'title': 'Contact'
    }
    return render(request, 'catalog/contact.html', context)


# Function Based View
# def products(request):
#     product_list = Product.objects.all()
#     context = {
#         'product_list': product_list,
#         'title': 'Products page'
#     }
#     return render(request, 'catalog/product_list.html', context)


# Class Based View the same as 'def products(request):' (previous function)
class ProductListView(LoginRequiredMixin, UserIsVerified, ListView):
    model = Product


# FBV
# def product(request, pk):
# GET request
#     product = Product.objects.get(pk=pk)
#     context = {
#         'product': product
#     }
#     return render(request, 'catalog/product_detail.html', context)


# CBV
class ProductDetailView(LoginRequiredMixin, UserIsVerified, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['versions'] = Version.objects.filter(product=self.object)
        return context_data


class ProductCreateView(LoginRequiredMixin, UserIsVerified, CreateView):
    model = Product
    success_url = reverse_lazy('catalog:products')
    form_class = ProductCreateForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Formset
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        user = self.request.user
        self.object.user = user

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserIsVerified, UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:products')
    form_class = ProductCreateForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Formset
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, UserIsVerified, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')


@login_required
@user_passes_test(lambda u: u.is_verified, login_url='users/verify_email/')
def category_list(request):
    context = {
        'object_list': get_queryset_from_models(Category),
        'title': 'Categories'
    }
    return render(request, 'catalog/category_list.html', context)

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'album.css' %}" rel="stylesheet">
</head>

<body>

<header>

    <div class="collapse bg-light" id="navbarHeader">
        {% include 'catalog/includes/inc_main_manu.html' %}
    </div>
    <div class="navbar navbar-light bg-light box-shadow">
        <img src="/media/tree.png" width="50" height="50">
        <div class="container d-flex justify-content-between">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}" type="button" class="btn btn-outline-danger" >Logout</a>
                    {% if user.is_verified %}
                        <a href="{% url 'users:profile' %}" type="button" class="btn btn-outline-dark" >Profile</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'users:login' %}" type="button" class="btn btn-outline-success" >Login</a>
                    <a href="{% url 'users:register' %}" type="button" class="btn btn-success">Sign-up</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<main role="main">
    {% if title %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>
    {% endif %}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% block content%}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            M
        </p>
        <p>&copy; {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html'%}
{% block content %}

{% for category in object_list %}
<div class="col-6">
    <br>
    <div class="card">
        <div class="card-header">
            <h4>{{ category.name }}</h4>
        </div>
        <div class="card-body">
            <h5> Description: </h5>
            {% if category.description|length > 100 %}
            <h6 class="card-subtitle mb-2 text-body-secondary">
                {{ category.description|slice:"0:100" }}...
            </h6>
            {% else %}
            <h6 class="card-subtitle mb-2 text-body-secondary">
                {{ category.description }}
            </h6>
            {% endif %}
            <p class="card-text">Create time: {{ category.created_at }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html'%}

{% block content %}
<div class="card border mb-3" style="max-width: 36rem;">
    <div class="card-header">Contact</div>
    <div class="card-body text-dark">
        <h5 class="card-title">Contact number: +1 111 111 1111</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html'%}

{% block content %}

<div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <svg class="bd-placeholder-img rounded me-2" width=20 height="20" xmlns="http://www.w3.org/2000/svg"
             aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
            <rect width="100%" height="100%" fill="#267800"></rect>
        </svg>
        <strong class="me-auto">Munduzbek</strong>
        <small>now</small>
    </div>
    <div class="toast-body">
        Hello, this is home page!
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}


    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-5 shadow">
            <div class="modal-body p-9 text-center">
                <h5 class="mb-0">Delete this product?</h5>
                <p class="mb-0">{{ object.name }}</p>
            </div>
            <form class="modal-footer flex-nowrap p-0" method="post">
                {% csrf_token %}
                <button type="submit"
                        class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">
                    <strong>Yes, delete</strong></button>
                <a href="{% url 'blog:blog_list' %}" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0"
                        data-bs-dismiss="modal">No, cancel
                </a>
            </form>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<style>
p {
    word-break: break-all;
    white-space: normal;
}



</style>


<article class="blog-post">
    <p>{{ product.category }}</p>
    <img src="/media/{{product.image}}"/>
    <div>
        <h2 class="display-5 link-body-emphasis mb-1">{{ product.title }}</h2>
        <h5 class="card-title">Name: {{ product.name|title }}</h5>
        <p>
            Description: {{ product.description }}
        </p>
        <button type="button" class="btn btn-outline-success" style="max-width: 100%;">
            Buy For
            <h4>
                ${{ product.price }}
            </h4>
        </button>
        <hr>
    </div>
    {% for version in versions %}
    {% if version.tag == True %}
    <div class="card">
        <div class="card-header">
            Name of version: {{ version }}
        </div>
        <div class="card-body">
            Number of version: {{ version.number }}
            <p>Is active: {{ version.tag }} </p>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <p class="fw-light" align="right">Created date: {{ product.create_date}}</p>
    <p align="right"> Last update: {{ product.date_last_change }}</p>
</article>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Product
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Product
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load my_tags %}
{% if user.is_authenticated %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>To add product click button below </h4>
        </div>
        <div class="card-body">
            <a class="btn btn-outline-dark" type="button" href="{% url 'catalog:create_product' %}">Add Product</a>
        </div>
    </div>
    <br>
</div>

{% else %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h5>You cannot add products, first sign up or log in to your account</h5>
        </div>
        <div class="card-body">
            <a class="btn btn-outline-dark" type="button" href="{% url 'users:register' %}">SignUp</a>
            <a class="btn btn-outline-dark" type="button" href="{% url 'users:login' %}">LogIn</a>
        </div>
    </div>
    <br>
</div>

{% endif %}


{% for product in product_list %}
<br>
<div class="col-3">
    <div class="card">
        <h5 class="card-title">Author: {{ product.user }}</h5>
        <div class="card-header">
            <img class="card-img-top" src="{% mediapath product.image %}"
                 alt="Card image cap">
        </div>
        <div class="card-body">
            <h4 class="card-title">{{ product|title }}</h4>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ product.create_date }}</h6>
            <p class="card-text">{{ product.description|slice:"0:100" }}...</p>
            <h1 class="card-title pricing-card-title">{{ product.price }}$<small
                    class="text-muted">/peace</small>
            </h1>
            <a href="{% url 'catalog:product' product.id %}" class="btn btn-outline-primary">More</a>
            {% if product.user == user or user.is_staff %}
            <a href="{% url 'catalog:update_product' product.id %}" class="btn btn-outline-warning">Edit</a>
            {% endif %}
            <a href="{% url 'catalog:delete_product' product.id %}" class="btn btn-outline-danger">Delete</a>
        </div>
    </div>
</div>
{% endfor %}

</div>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html'%}
{% block content %}
{% load my_tags %}
{% for product in product_list %}
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{% mediapath product.image %}"
         alt="Card image cap">
    <div class="card-body">
        <h4 class="card-title">{{ product|title }}</h4>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ product.create_date }}</h6>
        <p class="card-text">{{ product.description|slice:"0:100" }}...</p>
        <h1 class="card-title pricing-card-title">{{ product.price }}$<small class="text-muted">/peace</small></h1>
        <a href="{% url 'catalog:product' product.id %}" class="btn btn-primary">More</a>
    </div>
</div>
{% endfor %}
{% endblock %}